# Generated by Django 5.0.6 on 2024-05-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients_beta',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions_beta',
            field=models.JSONField(default=dict),
        ),
    ]
